### ISSUE TITLE
Vue 3 TS & Vite - Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by NomisCZ** [permafrost-dev/vue-ray#3]
**Describe the bug**

If you install Vue 3 TS & Vite (https://v3.vuejs.org/guide/installation.html#vite) and run app (npm run dev), you got blank page and error in console.

```
Uncaught ReferenceError: global is not defined AsymmetricMatcher.js:10 
  | (anonymous) | @ | AsymmetricMatcher.js:10
-- | -- | -- | --
  | (anonymous) | @ | chunk.SC3K7AYW.js?v=ff6d51f2:11
  | (anonymous) | @ | index.js:8
  | (anonymous) | @ | chunk.SC3K7AYW.js?v=ff6d51f2:11
  | (anonymous) | @ | web.esm.mjs:5
  | (anonymous) | @ | chunk.SC3K7AYW.js?v=ff6d51f2:11
  | (anonymous) | @ | vue3.mjs:19
```

**To Reproduce**

1. Install Vue with Vite, install Vue Ray plugin
```
$ npm init @vitejs/app <project-name>
$ cd <project-name>
$ npm install
$ npm install vue-ray
```

2. Import Vue Ray package (main.ts)
```
import { createApp } from 'vue'
import App from './App.vue'

import RayPlugin from 'vue-ray';

const app = createApp(App);
app.use(RayPlugin, { interceptErrors: true });
app.mount('#app');
```

3. Run
```
$ npm run dev
```

**Expected behavior**

![image](https://user-images.githubusercontent.com/7500606/109035268-c2487f80-76c8-11eb-8fc8-d92ed9ccf613.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/7500606/109034381-e061b000-76c7-11eb-8efc-6d5737c1def9.png)

**Environment (please complete the following information):**

 - OS: Windows 10
 - Vue Version: 3.0.5
 - Language & Version: Vite 2.0.1, TypeScript 4.1.3, Vite Vue plugin 1.1.4

**Additional context**
~

**Comment by patinthehat** [comment]
Thanks, I'm looking into this and will update soon.

**Comment by patinthehat** [comment]
@NomisCZ please run `npm update` _(you need the `node-ray` packge v1.8.4 or greater)_.  
Does this resolve the issue?

**Comment by NomisCZ** [comment]
> @NomisCZ please run `npm update` _(you need the `node-ray` packge v1.8.4 or greater)_.
> Does this resolve the issue?

Thank you! Works perfectly.

**Comment by ilijanovic** [comment]
Do following:

Go to `vite.config.ts`

Add following: 
```
  define: {
    global: {},
  },
```

It should look like this now:


```
export default defineConfig({
  plugins: [vue()],
  define: {
    global: {},
  },
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
});
```

**Comment by mmdjiji** [comment]
> Do following:
> 
> Go to `vite.config.ts`
> 
> Add following:
> 
> ```
>   define: {
>     global: {},
>   },
> ```
> 
> It should look like this now:
> 
> ```
> export default defineConfig({
>   plugins: [vue()],
>   define: {
>     global: {},
>   },
>   resolve: {
>     alias: {
>       "@": fileURLToPath(new URL("./src", import.meta.url)),
>     },
>   },
> });
> ```

After doing this, it wouldn't shows `global is not defined` but shows:
```
ReferenceError: Buffer is not defined
    at node_modules/.pnpm/mqtt-packet@6.10.0/node_modules/mqtt-packet/constants.js (constants.js:46:34)
    at __require2 (chunk-3444LDKZ.js?v=8583e65a:36:50)
    at node_modules/.pnpm/mqtt-packet@6.10.0/node_modules/mqtt-packet/parser.js (parser.js:4:19)
    at __require2 (chunk-3444LDKZ.js?v=8583e65a:36:50)
    at node_modules/.pnpm/mqtt-packet@6.10.0/node_modules/mqtt-packet/mqtt.js (mqtt.js:1:18)
    at __require2 (chunk-3444LDKZ.js?v=8583e65a:36:50)
    at node_modules/.pnpm/mqtt@4.3.7/node_modules/mqtt/lib/client.js (client.js:10:20)
    at __require2 (chunk-3444LDKZ.js?v=8583e65a:36:50)
    at node_modules/.pnpm/mqtt@4.3.7/node_modules/mqtt/lib/connect/index.js (index.js:3:20)
    at __require2 (chunk-3444LDKZ.js?v=8583e65a:36:50)
```

**Comment by jgb-solutions** [comment]
thanks @ilijanovic ! But can anyone tell me why it's happening?

**Comment by MichaelJE** [comment]
Hello everyone, I'm brand new to this.
I decided to inspect what's going on internally and the solution provided from a year ago breaks the builds.

So we have 2 scenarios:

1. Having no definition would cause our source code to collide with the vite defined rollup builds
2. Having a definition would cause the serve colliding with our source code

So my solution was to set the vite.config.js based on commands:

`

    // vite.config.ks
    const definitions = {
        // this can be empty or have some config
    };

    // Conditionally set a command
    if (command === 'serve') {
        definitions.global = {};
    }

    return defineConfig({
       ....
       define: {
          ...definitions
       },
       ...
    })

`
